import type { Category, Transaction } from '@/lib/types';
import {
  Briefcase,
  Gift,
  HeartPulse,
  Home,
  Utensils,
  Car,
  Plane,
  ShieldAlert,
  GraduationCap,
  Sparkles,
  ShoppingBag,
  CircleDollarSign,
  Factory,
} from 'lucide-react';

export const categories: Category[] = [
  {
    id: 'income',
    name: 'Income',
    icon: CircleDollarSign,
    subcategories: [
      { id: 'income_monthly', name: 'Monthly' },
      { id: 'income_appa_fd_interest', name: 'Appa FD Interest' },
      { id: 'income_fruits', name: 'Fruits' },
      { id: 'income_food_snack', name: 'Food & Snack' },
      { id: 'income_gift', name: 'Gift' },
      { id: 'income_medical', name: 'Medical' },
      { id: 'income_emergency', name: 'Emergency' },
      { id: 'income_home', name: 'Home' },
      { id: 'income_tour', name: 'Tour' },
      { id: 'income_dk_exp', name: 'Dk Exp' },
      { id: 'income_dk_professional', name: 'Dk Professional' },
      { id: 'income_nisha', name: 'Nisha' },
      { id: 'income_wfo', name: 'WFO' },
    ],
  },
  {
    id: 'monthly',
    name: 'Monthly',
    icon: Utensils,
    subcategories: [
      { id: 'monthly_grocery', name: 'Grocery' },
      { id: 'monthly_petrol', name: 'petrol' },
      { id: 'monthly_veg', name: 'Veg' },
      { id: 'monthly_non_veg', name: 'Non-veg' },
      { id: 'monthly_gas', name: 'Gas' },
      { id: 'monthly_dk_appa', name: 'Dk Appa' },
      { id: 'monthly_nisha_amma', name: 'Nisha Amma' },
      { id: 'monthly_milk', name: 'Milk' },
      { id: 'monthly_egg', name: 'Egg' },
      { id: 'monthly_anna_exp', name: 'Anna Exp' },
      { id: 'monthly_electrical', name: 'Electrical' },
      { id: 'monthly_others', name: 'Others' },
    ],
  },
  {
    id: 'food_snack',
    name: 'Food & Snack',
    icon: Utensils,
    subcategories: [
      { id: 'food_snack_food', name: 'Food' },
      { id: 'food_snack_snacks', name: 'Snacks' },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    icon: Sparkles,
    subcategories: [
      { id: 'fruits_fruits', name: 'Fruits' },
      { id: 'fruits_nuts', name: 'Nuts' },
    ],
  },
  {
    id: 'gift',
    name: 'Gift',
    icon: Gift,
    subcategories: [
      { id: 'gift_relatives', name: 'Relatives' },
      { id: 'gift_close_relatives', name: 'Close Relatives' },
      { id: 'gift_friends', name: 'Friends' },
      { id: 'gift_neighbour', name: 'Neighbour' },
      { id: 'gift_donation', name: 'Donation' },
    ],
  },
  {
    id: 'medical',
    name: 'Medical',
    icon: HeartPulse,
    subcategories: [
      { id: 'medical_hospital_bill', name: 'Hospital Bill' },
      { id: 'medical_medical_bill', name: 'Medical Bill' },
      { id: 'medical_lab_test', name: 'Lab test' },
      { id: 'medical_health_insurance', name: 'Health Insurance' },
      { id: 'medical_others', name: 'Others' },
      { id: 'medical_travel', name: 'Travel' },
      { id: 'medical_term_insurance', name: 'Term Insurance' },
      { id: 'medical_pregnancy', name: 'Pregnancy' },
      { id: 'medical_food', name: 'Food' },
    ],
  },
  {
    id: 'tour',
    name: 'Tour',
    icon: Plane,
    subcategories: [
      { id: 'tour_travel', name: 'Travel' },
      { id: 'tour_stay', name: 'Stay' },
      { id: 'tour_food', name: 'Food' },
      { id: 'tour_entry_fee', name: 'Entry Fee' },
      { id: 'tour_shopping', name: 'Shopping' },
      { id: 'tour_tips_donation', name: 'Tips+Donation' },
      { id: 'tour_outing', name: 'Outing' },
      { id: 'tour_outing_food', name: 'Outing Food' },
    ],
  },
  {
    id: 'emergency',
    name: 'Emergency',
    icon: ShieldAlert,
    subcategories: [
      { id: 'emergency_home', name: 'Home' },
      { id: 'emergency_medical', name: 'Medical' },
      { id: 'emergency_tour', name: 'Tour' },
      { id: 'emergency_gift', name: 'Gift' },
      { id: 'emergency_bike', name: 'Bike' },
    ],
  },
  {
    id: 'home',
    name: 'Home',
    icon: Home,
    subcategories: [
      { id: 'home_electrical', name: 'Electrical' },
      { id: 'home_plumbing', name: 'Plumbing' },
      { id: 'home_construction', name: 'Construction' },
      { id: 'home_utensils', name: 'Utensils' },
      { id: 'home_farm_garden', name: 'Farm & Garden' },
      { id: 'home_decoration', name: 'Decoration' },
      { id: 'home_land_maintenance', name: 'Land Maintenance' },
    ],
  },
  {
    id: 'dk_professional',
    name: 'DK professional',
    icon: GraduationCap,
    subcategories: [
      { id: 'dk_professional_subscriptions', name: 'Subscriptions' },
      { id: 'dk_professional_meetups', name: 'Meetups' },
      { id: 'dk_professional_shopping', name: 'Shopping' },
    ],
  },
  {
    id: 'nisha',
    name: 'Nisha',
    icon: Sparkles,
    subcategories: [
      { id: 'nisha_invesment', name: 'Invesment' },
      { id: 'nisha_mobile', name: 'Mobile' },
      { id: 'nisha_personal_grooming', name: 'Personal Grooming' },
      { id: 'nisha_gift', name: 'Gift' },
      { id: 'nisha_office', name: 'Office' },
      { id: 'nisha_borrow', name: 'Borrow' },
      { id: 'nisha_cash_rtn', name: 'Cash Rtn' },
    ],
  },
  {
    id: 'dk',
    name: 'Dk',
    icon: Sparkles,
    subcategories: [
      { id: 'dk_invesment', name: 'Invesment' },
      { id: 'dk_mobile_internet', name: 'Mobile&Internet' },
      { id: 'dk_personal_grooming', name: 'Personal Grooming' },
      { id: 'dk_gift', name: 'Gift' },
      { id: 'dk_borrow', name: 'Borrow' },
      { id: 'dk_subscriptions', name: 'Subscriptions' },
      { id: 'dk_others', name: 'Others' },
      { id: 'dk_office_expense', name: 'Office expense' },
      { id: 'dk_cash_rtn', name: 'Cash Rtn' },
    ],
  },
  {
    id: 'wfo',
    name: 'WFO',
    icon: Factory,
    subcategories: [
      { id: 'wfo_travel', name: 'Travel' },
      { id: 'wfo_food', name: 'Food' },
      { id: 'wfo_home', name: 'Home' },
      { id: 'wfo_gift', name: 'Gift' },
      { id: 'wfo_local_travel', name: 'Local Travel' },
      { id: 'wfo_internet_subscriptions', name: 'Internet+ subscriptions' },
      { id: 'wfo_sports', name: 'Sports' },
      { id: 'wfo_monthly', name: 'Monthly' },
      { id: 'wfo_dmart', name: 'DMart' },
      { id: 'wfo_quick_commerce_app', name: 'Quick Commerce App' },
    ],
  },
];


export const transactions: Transaction[] = [
  {
    id: 'txn1',
    date: '2024-07-20',
    time: '12:30',
    description: 'Weekly groceries',
    amount: 125.5,
    category: 'Monthly',
    subcategory: 'Grocery',
    paidBy: 'Chase Sapphire',
  },
  {
    id: 'txn2',
    date: '2024-07-20',
    time: '19:00',
    description: 'Dinner with friends',
    amount: 85.0,
    category: 'Food & Snack',
    subcategory: 'Food',
    paidBy: 'Amex Gold',
  },
  {
    id: 'txn3',
    date: '2024-07-19',
    time: '08:15',
    description: 'Fuel for car',
    amount: 132.0,
    category: 'Monthly',
    subcategory: 'petrol',
    paidBy: 'Debit Card',
  },
  {
    id: 'txn4',
    date: '2024-07-18',
    time: '15:45',
    description: 'New shirt',
    amount: 150.0,
    category: 'DK professional',
    subcategory: 'Shopping',
    paidBy: 'Chase Sapphire',
  },
  {
    id: 'txn5',
    date: '2024-07-15',
    time: '10:00',
    description: 'Netflix monthly subscription',
    amount: 15.49,
    category: 'Dk',
    subcategory: 'Subscriptions',
    paidBy: 'Amex Gold',
  },
  {
    id: 'txn6',
    date: '2024-07-15',
    time: '14:20',
    description: 'Ibuprofen from CVS',
    amount: 9.99,
    category: 'Medical',
    subcategory: 'Medical Bill',
    paidBy: 'Cash',
  },
];
