import type { Category, Transaction } from '@/lib/types';
import {
  ShoppingCart,
  Utensils,
  Car,
  FileText,
  Film,
  HeartPulse,
  Home,
  BookOpen,
} from 'lucide-react';

export const categories: Category[] = [
  {
    id: 'food',
    name: 'Food & Dining',
    icon: Utensils,
    subcategories: [
      { id: 'groceries', name: 'Groceries' },
      { id: 'restaurants', name: 'Restaurants' },
      { id: 'cafes', name: 'Cafes' },
    ],
  },
  {
    id: 'transport',
    name: 'Transportation',
    icon: Car,
    subcategories: [
      { id: 'fuel', name: 'Fuel' },
      { id: 'public_transport', name: 'Public Transport' },
      { id: 'ride_sharing', name: 'Ride Sharing' },
    ],
  },
  {
    id: 'shopping',
    name: 'Shopping',
    icon: ShoppingCart,
    subcategories: [
      { id: 'clothing', name: 'Clothing' },
      { id: 'electronics', name: 'Electronics' },
      { id: 'gifts', name: 'Gifts' },
    ],
  },
  {
    id: 'bills',
    name: 'Bills & Utilities',
    icon: FileText,
    subcategories: [
      { id: 'rent', name: 'Rent' },
      { id: 'electricity', name: 'Electricity' },
      { id: 'internet', name: 'Internet' },
      { id: 'phone', name: 'Phone' },
    ],
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: Film,
    subcategories: [
      { id: 'movies', name: 'Movies' },
      { id: 'concerts', name: 'Concerts' },
      { id: 'subscriptions', name: 'Subscriptions' },
    ],
  },
  {
    id: 'health',
    name: 'Health & Wellness',
    icon: HeartPulse,
    subcategories: [
      { id: 'pharmacy', name: 'Pharmacy' },
      { id: 'doctor', name: 'Doctor' },
      { id: 'gym', name: 'Gym' },
    ],
  },
   {
    id: 'housing',
    name: 'Housing',
    icon: Home,
    subcategories: [
      { id: 'rent_mortgage', name: 'Rent/Mortgage' },
      { id: 'property_tax', name: 'Property Tax' },
      { id: 'repairs', name: 'Repairs' },
    ],
  },
  {
    id: 'education',
    name: 'Education',
    icon: BookOpen,
    subcategories: [
      { id: 'tuition', name: 'Tuition' },
      { id: 'books', name: 'Books' },
      { id: 'courses', name: 'Online Courses' },
    ],
  },
];

export const transactions: Transaction[] = [
  {
    id: 'txn1',
    date: '2024-07-20',
    time: '12:30',
    description: 'Trader Joe\'s weekly groceries',
    amount: 125.5,
    category: 'Food & Dining',
    subcategory: 'Groceries',
    paidBy: 'Chase Sapphire',
  },
  {
    id: 'txn2',
    date: '2024-07-20',
    time: '19:00',
    description: 'Dinner with friends at The Italian Place',
    amount: 85.0,
    category: 'Food & Dining',
    subcategory: 'Restaurants',
    paidBy: 'Amex Gold',
  },
  {
    id: 'txn3',
    date: '2024-07-19',
    time: '08:15',
    description: 'Monthly MetroCard top-up',
    amount: 132.0,
    category: 'Transportation',
    subcategory: 'Public Transport',
    paidBy: 'Debit Card',
  },
  {
    id: 'txn4',
    date: '2024-07-18',
    time: '15:45',
    description: 'New pair of running shoes',
    amount: 150.0,
    category: 'Shopping',
    subcategory: 'Clothing',
    paidBy: 'Chase Sapphire',
  },
  {
    id: 'txn5',
    date: '2024-07-15',
    time: '10:00',
    description: 'Netflix monthly subscription',
    amount: 15.49,
    category: 'Entertainment',
    subcategory: 'Subscriptions',
    paidBy: 'Amex Gold',
  },
  {
    id: 'txn6',
    date: '2024-07-15',
    time: '14:20',
    description: 'Ibuprofen from CVS',
    amount: 9.99,
    category: 'Health & Wellness',
    subcategory: 'Pharmacy',
    paidBy: 'Cash',
  },
  {
    id: 'txn7',
    date: '2024-07-12',
    time: '09:00',
    description: 'Gasoline for car',
    amount: 55.20,
    category: 'Transportation',
    subcategory: 'Fuel',
    paidBy: 'Debit Card',
  },
  {
    id: 'txn8',
    date: '2024-07-10',
    time: '11:00',
    description: 'Electricity Bill',
    amount: 75.60,
    category: 'Bills & Utilities',
    subcategory: 'Electricity',
    paidBy: 'Bank Transfer',
  },
  {
    id: 'txn9',
    date: '2024-07-08',
    time: '17:00',
    description: 'Starbucks coffee meeting',
    amount: 12.75,
    category: 'Food & Dining',
    subcategory: 'Cafes',
    paidBy: 'Cash',
  },
  {
    id: 'txn10',
    date: '2024-07-05',
    time: '20:00',
    description: 'Tickets to see "Dune: Part Two"',
    amount: 32.00,
    category: 'Entertainment',
    subcategory: 'Movies',
    paidBy: 'Chase Sapphire',
  },
];
